// @atlas/ui — hooks barrel export

export { useHotkeys, splitHotkey } from './useHotkeys'
export type { HotkeyHandler, UseHotkeysReturn } from './useHotkeys'

export { useControllableState } from './useControllableState'
export type { ControllableStateOptions } from './useControllableState'

export { useDebouncedValue } from './useDebouncedValue'
export { usePrevious } from './usePrevious'
export { useInterval, useTimeout } from './useTimer'
export { useLatest } from './useLatest'
export { useIsMounted } from './useIsMounted'
export { useDisclosure } from './useDisclosure'
export { useKeyPress } from './useKeyPress'
export type { UseKeyPressReturn } from './useKeyPress'
export { useIsKeyDown } from './useIsKeyDown'
export type { UseIsKeyDownReturn } from './useIsKeyDown'
export { useRovingFocus } from './useRovingFocus'
export type { RovingFocusOptions } from './useRovingFocus'
export { useFocusTrap } from './useFocusTrap'
export { useScrollPosition } from './useScrollPosition'
export type { ScrollPosition } from './useScrollPosition'

export { usePointerDrag } from './usePointerDrag'
export type { PointerDragHandlers, UsePointerDragReturn } from './usePointerDrag'
export { useMultiSelect } from './useMultiSelect'
export type { MultiSelectOptions, UseMultiSelectReturn } from './useMultiSelect'
export { useListState } from './useListState'
export type { UseListStateReturn } from './useListState'
export { useAsync } from './useAsync'
export type { AsyncState } from './useAsync'
export { useDebouncedCallback } from './useDebouncedCallback'
export { usePagination } from './usePagination'
export type { PaginationOptions, UsePaginationReturn } from './usePagination'
export { useCopyState } from './useCopyState'
export { useHover } from './useHover'
export { useFocusVisible } from './useFocusVisible'
export { useWindowQuery, useIsCompact } from './useWindowQuery'
export type { WindowQuery } from './useWindowQuery'
export { useCounter } from './useCounter'
export { useIdle } from './useIdle'
