// @atlas/ui — desktop barrel export
// Desktop-app chrome: system dialogs, status/feedback, nav & content helpers.

export { UnsavedChangesDialog } from './UnsavedChangesDialog'
export type { UnsavedChangesDialogProps } from './UnsavedChangesDialog'
export { AboutDialog } from './AboutDialog'
export type { AboutDialogProps } from './AboutDialog'
export { CrashDialog } from './CrashDialog'
export type { CrashDialogProps } from './CrashDialog'
export { ReleaseNotesDialog } from './ReleaseNotesDialog'
export type { ReleaseNotesDialogProps } from './ReleaseNotesDialog'
export { LicensesDialog } from './LicensesDialog'
export type { LicensesDialogProps, LicenseEntry } from './LicensesDialog'
export { PermissionGate } from './PermissionGate'
export type { PermissionGateProps } from './PermissionGate'

export { ConnectBar } from './ConnectBar'
export type { ConnectBarProps } from './ConnectBar'
export { DownloadCard } from './DownloadCard'
export type { DownloadCardProps, DownloadState } from './DownloadCard'
export { AutoSavePill } from './AutoSavePill'
export type { AutoSavePillProps } from './AutoSavePill'
export { PropertyGrid } from './PropertyGrid'
export type { PropertyGridProps, PropertyGridItem } from './PropertyGrid'
export { ThemeSwitcher } from './ThemeSwitcher'
export type { ThemeSwitcherProps } from './ThemeSwitcher'
export { FindBar } from './FindBar'
export type { FindBarProps } from './FindBar'
export { ZoomControls } from './ZoomControls'
export type { ZoomControlsProps } from './ZoomControls'
export { WordCountBar } from './WordCountBar'
export type { WordCountBarProps } from './WordCountBar'
export { VersionFooter } from './VersionFooter'
export type { VersionFooterProps } from './VersionFooter'
export { ShortcutSettingsList } from './ShortcutSettingsList'
export type { ShortcutSettingsListProps, ShortcutSettingRow } from './ShortcutSettingsList'
export { RecentFilesList } from './RecentFilesList'
export type { RecentFilesListProps, RecentFile } from './RecentFilesList'
export { ToolboxRail } from './ToolboxRail'
export type { ToolboxRailProps, ToolboxTool } from './ToolboxRail'
export { PreviewPane } from './PreviewPane'
export type { PreviewPaneProps } from './PreviewPane'
export { GroupedSidebarNav } from './GroupedSidebarNav'
export type { GroupedSidebarNavProps, NavGroup, NavItem } from './GroupedSidebarNav'
export { FavoritesBar } from './FavoritesBar'
export type { FavoritesBarProps, FavoriteItem } from './FavoritesBar'
export { EmojiPicker } from './EmojiPicker'
export type { EmojiPickerProps } from './EmojiPicker'
export { FontPicker } from './FontPicker'
export type { FontPickerProps, FontChoice } from './FontPicker'
